[alembic]
script_location = alembic
sqlalchemy.url = sqlite:///./deepwork.db

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = simple

[logger_root]
level = WARN
handlers = console

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
level = NOTSET
formatter = simple
args = (sys.stderr,)

[formatter_simple]
format = %(levelname)-5.5s [%(name)s] %(message)s